version: '3.7'

x-ruby: &ruby
  build:
    context: .
    dockerfile: Dockerfile.dev
  volumes:
    - ./:/app
    # Saving gems to volume makes bundle install faster (from the second time
    # on).
    - bundler_volume:/usr/local/bundle

services:
  ruby:
    <<: *ruby
    command:
      - irb
    # For binding.pry.
    tty: true
    stdin_open: true
    environment:
      - SPARROW_CONFIG=/app/sparrow.example.yml
      - PUBSUB_EMULATOR_HOST=pubsub:8085
    depends_on:
      - pubsub

  bundler:
    <<: *ruby
    command:
      - bundle
      - install

  pubsub:
    image: google/cloud-sdk:288.0.0
    command:
      - gcloud
      - beta
      - emulators
      - pubsub
      - start
      - --host-port=0.0.0.0:8085

volumes:
  bundler_volume:
